repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff  # Run the linter.
      args: [ --fix ]
    - id: ruff-format  # Run the formatter

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.0
  hooks:
  - id: mypy
