name: Update Changelog

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

permissions:
  contents: read

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate changelog
        run: |
          pip install git-cliff
          git cliff --latest --prepend CHANGELOG.md --config ./.config/cliff.toml

      - name: Commit
        run: |
          git checkout main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
