name: CI Automation
on: [push, pull_request]

jobs:

  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Test with Unittest
        run: PYTHONPATH=./src python -m unittest discover -s tests -p "test_*.py" > /dev/null
