name: CI Automation
on: [push, pull_request]

jobs:

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Python Code with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: "check"

      - name: Format Python Code with Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Test with Pytest
        run: pytest
