on: ["push", "pull_request"]

name: Update Test Coverage

permissions:
  contents: read

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv (faster alternative to pip)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.4"
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install coveralls pytest
          uv pip install -r pyproject.toml

      - name: Generate Coverage Report
        env:
          PYTHONPATH: ./src
        run: |
          coverage run -m pytest --doctest-modules src
          coverage xml

      - name: Upload Report to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
        run: coveralls

      - name: Upload Report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
