on: ["push", "pull_request"]

name: Coveralls Test Coverage

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coveralls
          pip install pytest

      - name: Run Coverall
        env:
          PYTHONPATH: ./src
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
        run: |
          coverage run -m pytest tests/
          coveralls
