on: ["push", "pull_request"]

name: Coveralls Test Coverge

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run Coverall
        run: |
          pip install coveralls
          coverage run --source=src -m pytest tests/
          coveralls
