name: Deploy Sphinx Documentation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv (faster alternative to pip)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.4"
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml --extra docs

      - name: Generate rst files
        run: sphinx-apidoc -o docs/source src/mastermind -f --templatedir=docs/source/_templates --maxdepth=2 --module-first

      - name: Build documentation
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
