name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    name: Build and upload release artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv (faster alternative to pip)
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          activate-environment: 'true'
          enable-cache: true

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Build release
        run: uv build

      - name: Test release (wheel)
        run: uv run --isolated --all-extras --with dist/*.whl python src/main/python/mastermind/demo.py

      - name: Test release (source distribution)
        run: uv run --isolated --all-extras --with dist/*.tar.gz python src/main/python/mastermind/demo.py

      - name: Upload release
        run: uv publish --trusted-publishing always