name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    name: Build and upload release artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv (faster alternative to pip)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.4"
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Build release
        run: uv build

      - name: Test release (wheel)
        run: uv run --isolated --all-extras --with dist/*.whl pytest --doctest-modules src


      - name: Test release (source distribution)
        run: uv run --isolated --all-extras --with dist/*.tar.gz pytest --doctest-modules src

      - name: Upload release
        run: uv publish --trusted-publishing always
